FROM php:8.5-fpm

ENV OPCACHE_VALIDATE_TIMESTAMPS=0
ENV APP_ENV=prod

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \
    && apt update && apt install -y nginx \
    && install-php-extensions intl apcu zip pdo_mysql

RUN ln -s ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini \
    && sed -i -e "s/^ *memory_limit.*/memory_limit = 512M/g" ${PHP_INI_DIR}/php.ini

COPY docker/php/conf.d/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
COPY docker/php/conf.d/family-app.ini ${PHP_INI_DIR}/conf.d/family-app.ini
COPY docker/nginx/conf.d/default.prod.conf /etc/nginx/conf.d/default.conf
RUN rm -f /etc/nginx/sites-enabled/default

ENV COMPOSER_ALLOW_SUPERUSER=1
COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY app /var/www/html
RUN composer install --prefer-dist --no-progress --no-suggest -o --no-interaction --ignore-platform-reqs

COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]
