name: Docker Image CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          DATE_TIME="$(date +'%Y.%m.%d.%H.%M')"
          echo "DATE_TIME=$DATE_TIME" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/family-app-backend:$DATE_TIME \
            -f docker/php/Dockerfile.prod . --platform=linux/amd64
          docker push ghcr.io/${{ github.repository_owner }}/family-app-backend:$DATE_TIME
          docker tag ghcr.io/${{ github.repository_owner }}/family-app-backend:$DATE_TIME \
            ghcr.io/${{ github.repository_owner }}/family-app-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/family-app-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          DATE_TIME="$(date +'%Y.%m.%d.%H.%M')"
          echo "DATE_TIME=$DATE_TIME" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/family-app-frontend:$DATE_TIME \
            -f docker/frontend/Dockerfile . --platform=linux/amd64
          docker push ghcr.io/${{ github.repository_owner }}/family-app-frontend:$DATE_TIME
          docker tag ghcr.io/${{ github.repository_owner }}/family-app-frontend:$DATE_TIME \
            ghcr.io/${{ github.repository_owner }}/family-app-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/family-app-frontend:latest
